# Generated by Django 5.0.2 on 2024-04-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=15)),
                ('Levels', models.IntegerField()),
                ('period', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('seating_capacity', models.IntegerField()),
                ('ClassTypeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClassRooms', to='FinalApp.classtype')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassRooms', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Content', models.CharField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('DepartmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Adertisement', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DM', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='DM_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField()),
                ('seen', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('DMId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.dm')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('number_of_groups', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('roles', models.ManyToManyField(to='FinalApp.role', verbose_name='roles')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('number_of_groups', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('LeveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Specializations', to='FinalApp.level')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('number_of_students', models.IntegerField()),
                ('LeveId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to='FinalApp.level')),
                ('SpecializationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to='FinalApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('AccountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student', to='FinalApp.account')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='FinalApp.department')),
                ('GroupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Students', to='FinalApp.group')),
                ('SpecializationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Studens', to='FinalApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField()),
                ('seen', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('GrouplId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.group')),
                ('LevelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.level')),
                ('SpeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Content', models.CharField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentNotes', to='FinalApp.department')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes', to='FinalApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('HasLab', models.BooleanField()),
                ('TheoreticalHours', models.IntegerField()),
                ('LabHours', models.IntegerField(null=True)),
                ('Specialization', models.CharField(max_length=50, null=True)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Academic_Degree', models.CharField(max_length=15)),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='FinalApp.account')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='SharedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmensId', models.ManyToManyField(to='FinalApp.department', verbose_name='Departments')),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SharedTeachers', to='FinalApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsLab', models.BooleanField()),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.subject')),
                ('Teachers', models.ManyToManyField(to='FinalApp.teacher', verbose_name='Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.semestersubject')),
                ('Teachers', models.ManyToManyField(to='FinalApp.teacher', verbose_name='Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.department')),
                ('GroupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.group')),
                ('LevelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.level')),
                ('SubjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.semestersubject')),
                ('SpecId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.specialization')),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='FinalApp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='dm',
            name='TeacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DM', to='FinalApp.teacher'),
        ),
        migrations.CreateModel(
            name='Constrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sun', models.BooleanField()),
                ('Mon', models.BooleanField()),
                ('Tue', models.BooleanField()),
                ('Wed', models.BooleanField()),
                ('Thu', models.BooleanField()),
                ('TeacherId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Constrains', to='FinalApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField()),
                ('date', models.DateTimeField()),
                ('seen', models.BooleanField()),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Content', models.CharField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherNotes', to='FinalApp.department')),
                ('TeacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes', to='FinalApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeTable', to='FinalApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable_Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=20)),
                ('Day', models.CharField(max_length=20)),
                ('ClassRoomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TLectures', to='FinalApp.classroom')),
                ('LectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TLecture', to='FinalApp.lecture')),
                ('TimetableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TLecture', to='FinalApp.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Compensation_Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('NewTime', models.CharField(max_length=20, null=True)),
                ('NewRoomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CompensationLecture', to='FinalApp.classroom')),
                ('TimeTableLecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompensationLecture', to='FinalApp.timetable_lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Canceled_Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanceledLecture', to='FinalApp.department')),
                ('TimeTableLecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanceledLecture', to='FinalApp.timetable_lecture')),
            ],
        ),
    ]
