# Generated by Django 5.0.2 on 2024-04-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='number_of_groups',
        ),
        migrations.AddField(
            model_name='level',
            name='Specialization',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='LevelId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Students', to='FinalApp.level'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
    ]
