# Generated by Django 5.0.2 on 2024-04-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0002_remove_specialization_number_of_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='DepartmentId',
        ),
        migrations.AlterField(
            model_name='dm_notification',
            name='DMId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.department'),
        ),
    ]
