# Generated by Django 5.0.2 on 2024-05-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0003_remove_classroom_departmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DM', to='FinalApp.department', unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='AccountId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Account', to='FinalApp.account'),
        ),
    ]
