# Generated by Django 5.0.2 on 2024-05-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0004_alter_dm_departmentid_alter_teacher_accountid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='LeveId',
            new_name='LevelId',
        ),
    ]
