# Generated by Django 5.0.2 on 2024-05-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0005_rename_leveid_group_levelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='LeveId',
            new_name='LevelId',
        ),
    ]
