# Generated by Django 5.0.2 on 2024-05-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0006_rename_leveid_specialization_levelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersubject',
            name='Teachers',
            field=models.ManyToManyField(null=True, to='FinalApp.teacher', verbose_name='Teachers'),
        ),
    ]
