# Generated by Django 5.0.2 on 2024-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0009_alter_teacher_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernote',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
    ]
