# Generated by Django 5.0.2 on 2024-05-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0010_alter_teachernote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='student_notification',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='teacher_notification',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
    ]
