# Generated by Django 5.0.2 on 2024-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0011_alter_advertisement_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
