# Generated by Django 5.0.2 on 2024-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0013_alter_lecture_levelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
