# Generated by Django 5.0.2 on 2024-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0014_alter_level_name_alter_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
