# Generated by Django 5.0.2 on 2024-06-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0015_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedsubject',
            name='Teachers',
        ),
        migrations.AddField(
            model_name='selectedsubject',
            name='Teachers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FinalApp.teacher'),
            preserve_default=False,
        ),
    ]
