# Generated by Django 5.0.2 on 2024-06-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0016_remove_selectedsubject_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_notification',
            name='DepartmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DNotification', to='FinalApp.department'),
        ),
        migrations.AlterField(
            model_name='teacher_notification',
            name='TeacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.teacher'),
        ),
    ]
