# Generated by Django 5.0.2 on 2024-06-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0017_teacher_notification_departmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notification',
            name='DepartmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SNotification', to='FinalApp.department'),
        ),
        migrations.AlterField(
            model_name='student_notification',
            name='LevelId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification', to='FinalApp.level'),
        ),
    ]
