# Generated by Django 5.0.2 on 2024-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0018_student_notification_departmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm_notification',
            name='Title',
            field=models.CharField(default='subject', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dm_notification',
            name='Content',
            field=models.CharField(max_length=1000000),
        ),
    ]
