from .Tlecture import TLecture
from .lecture import lecture
from .department import Department
from .instructor import Instructor
from .meeting_time import MeetingTime
from .room import Room
from .level import Level
from .day import Day
from .group import Group
from .t_constrains import Teacher_Constrains
