from . import views
from django.urls import path

urlpatterns = [
path('LogIn',views.LogIn),
path('department',views.department),
path('department/<str:pk>',views.department_PK),
path('classroom',views.classroom),
path('classroom/<int:pk>',views.classroom_PK),
path('classType',views.classType),
path('students',views.students),
path('student',views.student),
path('student_timetable_day/<int:pk>',views.student_timetable_day),
path('student/<int:pk>',views.student_PK),

path('level',views.level),
path('level/<int:pk>',views.level_PK),
path('dep_levels/<str:pk>',views.dep_levels),
path('dep_groups/<str:pk>',views.dep_groups),
path('groups/<int:pk>',views.group_PK),
path('level_groups/<int:pk>',views.level_groups),
path('spec_groups/<int:pk>',views.spec_groups),
path('specialization/<int:pk>',views.spec),
path('lecture/<int:pk>',views.lecture_PK),
path('lecture',views.lecture),
path('dep_lectures/<str:pk>',views.get_lectures),
path('create_lectures/<str:pk>',views.create_lectures),
path('choose_subject',views.choose_subject),
path('unchoose_subject/<int:pk>',views.unchoose_subject),
path('empty_classroom/<str:day>',views.empty_classroom),
path('teacher_timetable/<int:pk>',views.teacher_timetable),
path('teacher',views.teacher),
path('dep_teachers/<str:pk>',views.dep_teacher),
path('teacher_with_shared/<str:pk>',views.dep_teacher_with_shared),
path('dep_teacher_of_subject/<int:pk>',views.dep_teacher_of_subject),
path('dep_subject_of_teacher/<int:pk>',views.dep_subject_of_teacher),
path('publish/<str:pk>',views.publish),
path('student_timetable/<int:pk>',views.student_timetable),
path('dep_sem_subject_of_teacher/<int:pk>',views.dep_sem_subject_of_teacher),
path('level_timetable/<str:pk>/<int:Lpk>',views.level_timetable),
path('create_timetable/<str:pk>',views.create_timetable),
path('timetable/<str:pk>',views.timetable),
path('DM/<int:pk>',views.get_DM),
path('another_teachers/<str:pk>',views.another_dep_teachers),
path('choose_teacher',views.choose_teacher),
path('shared_teacher/<str:pk>',views.shared_teacher),
path('shared_teacher_pk/<int:Spk>/<str:Dpk>',views.shared_teacher_pk),
path('teacher/<int:pk>',views.teacher_PK),
path('teacher_note',views.teacher_notes),
path('T_notification/<int:pk>',views.T_notification),
path('S_notification/<int:pk>',views.student_notification),
path('DM_notification/<int:pk>',views.DM_notification),
path('constrains',views.constrains),
path('constrains/<int:pk>',views.constrains_PK),
path('cancel_lecture',views.cancel_lecture),
path('canceled_lecture/<str:pk>',views.canceled_lecture),
path('del_canceled_lecture/<int:pk>',views.del_canceled_lecture),
path('Compensation_lecture',views.Compensation_lecture),
path('compensation_lecture/<int:pk>',views.compensation_pk),
path('dep_compensation/<str:pk>',views.dep_compensation),
path('student_compensation/<int:pk>',views.student_compensation),
path('teacher_compensation/<int:pk>',views.teacher_compensation),
path('student_canceled_lecture/<int:pk>',views.student_canceled_lecture),
path('teacher_canceled_lecture/<int:pk>',views.teacher_canceled_lecture),
path('get_timetable/<str:pk>',views.get_timetable),

path('advertisement',views.advertisement),
path('dep_advertisement/<str:pk>',views.dep_advertisement),
path('advertisement/<int:pk>',views.advertisement_pk),
path('create_timetable',views.create_timetable),
path('subject',views.subject),
path('dep_subject/<str:pk>',views.dep_subject),
path('subject/<int:pk>',views.subject_PK),
path('semester_subject',views.semester_subject),
path('dep_sem_subject/<str:pk>',views.dep_sem_subject),
path('semester_subject/<int:pk>',views.semestersubject_PK),
path('teacher_subject',views.teacher_Subject),
path('teacher_subject/<int:Spk>/<int:Tpk>',views.teacher_subject_pk),
path('dep_teacher_subject/<str:pk>',views.dep_teacher_subject),
path('dep_selected_subject/<str:pk>',views.dep_selected_subject),
path('show_student_notes/<str:pk>',views.show_student_notes),
path('show_teacher_notes/<str:pk>',views.show_teacher_notes),
path('teacher_timetable/<int:pk>',views.teacher_timetable),
path('teacher_day_timetable/<int:pk>',views.teacher_day_timetable),










]